### ISSUE TITLE
Modules don't properly get required when in folders

### ISSUE THREAD

**Issue by DerekJTrevens** [Sleitnick/AeroGameFramework#25] opened 2018-07-31 00:31 UTC
The Aero plugin seems to accept subcategory folders within the Modules and Shared folders, but the lazyload function errors when you index a module in one of these folders for the first time.

**Comment by Sleitnick** [comment] 2018-07-31 04:35
Actually subcategories with folders is not supported, but it should be. I think having support for subcategories via folders would be cool and useful for the framework. I'll add it to my backlog.

**Comment by Sleitnick** [comment] 2018-08-15 22:29
After further review, I have decided to not do this. I may come back to this later and implement it, but it would make sense to also allow nested modules within modules to be utilized too. The problem is that it isn't clear what those modules should be loaded as. For instance, if a module is inside a folder in the Services tab, does that mean it should be a Service, or simply loaded as a standard module?

Due to this, I have deemed it out of scope for now, but would love to come back to it later. Closing for now.

**Closed by Sleitnick** 2018-08-15 22:29 UTC
Labels: bug
