### ISSUE TITLE
AeroClient caches RemoteFunction results for too long

### ISSUE THREAD

**Issue by OverHash** [Sleitnick/AeroGameFramework#145] opened 2020-04-12 22:27 UTC
Take this simple repo - a service called `serverResponder` with this code
 ```lua
local serverResponder = { Client = {} }

function serverResponder.Client:Get(player, num)
	print(player.Name, num)
	
	return {num}
end

return serverResponder
```

and a controller with this code:
```lua
local module = {}

function module:Start()
	local serverResponder = module.Services.serverResponder
	
	for i = 1, 10 do
		print(i, serverResponder:Get(i))
	end
end

return module
```
You would not expect the return result from calling `serverResponder:Get` to cache, but in the current state, it will. This is because all the subsequent `for` loop calls connect to the code in AeroClient that cache when a promise exists. https://github.com/Sleitnick/AeroGameFramework/blob/73423b040e5b9e080a087e8f06e6bf9e621b9e0c/src/StarterPlayer/StarterPlayerScripts/Aero/Internal/AeroClient.client.lua#L118-L119

Output from this small repo:
```
[server print] OverHash 1
1 table: 0x2f8f5da39133ba88
2 table: 0x2f8f5da39133ba88
3 table: 0x2f8f5da39133ba88
4 table: 0x2f8f5da39133ba88
5 table: 0x2f8f5da39133ba88
6 table: 0x2f8f5da39133ba88
7 table: 0x2f8f5da39133ba88
8 table: 0x2f8f5da39133ba88
9 table: 0x2f8f5da39133ba88
10 table: 0x2f8f5da39133ba88
```
_as you can see, it only invokes the RemoteFunction once and caches the return result_

This is due to an implementation in the promise library that makes `Promise.Async` wait until the next `RunService.Heartbeat` to fire. Between the time of the first for loop call, and the last, some events have chained onto the same promise call.
This is unexpected behavior, we have a caching system on the client that will be cleared each heartbeat!

**Comment by Sleitnick** [comment] 2020-04-14 18:54
Thanks for the report! I will respond to your PR.

**Comment by Sleitnick** [comment] 2020-04-14 19:06
Thanks for the report! What this is highlighting is a larger issue at hand. The code is actually working as intended. However, the design is flawed. The current design makes a bad assumption that subsequent calls to a pending RemoteFunction response are idempotent.

The solution to this problem is probably just to remove the use of promises with the non-cached flow for RemoteFunctions on the client. It is more fair to assume that any repeated calls to a RemoteFunction are purposeful and non-idempotent, and thus any failure of such an assumption is up to the developer to fix.

------------

That's a long-winded way of basically saying that I will remove the promise for non-caching RemoteFunctions and just call the remote and return the result.

**Comment by Sleitnick** [comment] 2020-04-14 19:19
Fixed in https://github.com/Sleitnick/AeroGameFramework/commit/76cb3a32d1bf2321b2b71b706633e82178a814ef

**Closed by Sleitnick** 2020-04-14 19:19 UTC
Labels: bug
